AboutUs/urls.py
from django.urls import path
from . import views

app_name = 'about_us'

urlpatterns = [
    path('', views.aboutus, name='aboutus'),
    path('send_feedback', views.send, name='send'),
    path('submitted', views.submitted, name='submitted')
]

Events/urls.py
from django.urls import path
from .views import *

urlpatterns = [
    path('events', filter_events, name='filter_events'),
    path('', searchevents, name = 'searchevents'),
    path('events/<str:value>' , get_JSON_category, name = "filtered_events")
]

forum/urls.py
from django.urls import path
from .views import forum

urlpatterns = [
    path('', forum, name='forum'),
    # dilanjutkan ...
]

tugas1KD03/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('RegisterEvent/', include('RegisterEvent.urls')),
    path('AboutUs/', include('AboutUs.urls')),
    path('', include('Events.urls')),
    path('Forum/', include('forum.urls')),
    path('login/', include('loginPage.urls')),
]

Events/models.py
from django.db import models
from datetime import datetime

# Create your models here.

CATEGORIES = (
    ('general','General'),
    ('bigdata', 'Big Data'),
    ('software','Software'),
    ('machinelearning','Machine Learning'),
    ('webdev','Web Development'),
)

class Category(models.Model):

    name = models.CharField(max_length=50)
    age = models.IntegerField()
    category = models.CharField(max_length = 20, choices = CATEGORIES, default='general')
    
    

Events/forms.py
from django import forms
from django.forms import TextInput

from .models import Category

class CategoryForm(forms.ModelForm):
    
        # self.fields['age'].widget = TextInput(attrs={
        #     'id': 'fieldAge',
        #     'class': 'fieldz'
    class Meta:
        model = Category
        fields = ('category', 'name', 'age')
        labels = {
                'category'      : "Select Category",
                'name'          : "Your Name :",
                'age'           : "Age              :",
            }

    def __init__(self, *args, **kwargs):
        super(CategoryForm, self).__init__(*args, **kwargs)
        
        

        self.fields['name'].widget = TextInput(attrs={
            'id': 'fieldName',
            'class': 'fieldz',
        })

        self.fields['age'].widget = TextInput(attrs={
            'id': 'fieldAge',
            'class': 'fieldz',
        })

    

        

Events/views.py
from django.shortcuts import render, redirect
from RegisterEvent.models import Jadwal
from .models import Category
from .forms import CategoryForm
from django.http import JsonResponse


# Create your views here.
# def events(request):
#     return render(request,'events.html')

def searchevents(request):
    
    if request.method == "POST":
        form = CategoryForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('filter_events')
    else:
        form = CategoryForm()
    
    
    return render(request, 'searchevents.html', {'form' : form})


def get_JSON_category(request,value):
    # result = []
    # for event in Jadwal.objects.all():
    #     if event.category == value:
    #         result.append(event)
    # print(result)
    # return JsonResponse({"data": list(Jadwal.objects.all())})
    if value == 'General':
        val = "general"
    elif value == 'Big Data':
        val = "bigdata"
    elif value == 'Software':
        val = "software"
    elif value == 'Machine Learning':
        val = "machinelearning"
    elif value == 'Web Development':
        val = "webdevelopment"
    result = list(Jadwal.objects.filter(category=val).values())
    return JsonResponse({"data": result})




def filter_events(request):
    events = Jadwal.objects.all()
    
    return render(request, 'events.html', {'events': events})

Events/templates/events.html
{% extends 'navbar.html' %}
{% load static %}

{% block content %}
<div>
    <div class="container">
      <div class="row">
        <div class="col-sm-12 text-center">
          <br><br><br>
          <h2 id="Events">Events</h2><hr>
        </div>
      </div>

      <div class="row justify-content-center align-items-center">
        <div class="container backforms">
            <div class="article">
                
                <div class="article">
                    <div class="row">
                        {% for event in events %}
                            
                            <div class="col-sm-12 text-center formBox" id="boxEvent">
                                <p><strong>{{ event.name }}</strong></p>
                                <p>{{ event.date}}</p>
                                <p>{{ event.time }}</p>
                                <p>Rp. {{ event.entranceFee }}</p>
                                
                            </div>
                            
                            
                        {% endfor %}
                    </div>
                </div>
            </div>
        </div>
    </div>

    </div>
</div>


{% endblock %}

Events/templates/navbar.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
        integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
        <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}" >
    <title>Search-It-Event</title>
    
    <!-- <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
     -->
     <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.0/jquery.min.js"></script>
    <script src="//code.jquery.com/jquery-1.10.2.js"></script>
    <script src="//code.jquery.com/ui/1.11.2/jquery-ui.js"></script>
    <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js"></script>
    <script src="{% static 'Events.js' %}"></script>

</head>

<body>

    <nav class="navbar fixed-top navbar-expand-md my-nav navbar-right navbar-dark" id="navbarEvents">
        {% if user.is_authenticated %}
                
            <a class="nav-item nav-link ml-4 butPage" href="#" style="color: #262626; font-weight: 600;">Hello {{ user }}</a>
                
        {% else %}
                
            <a class="nav-item nav-link ml-4 butPage" href="#" style="color: #262626; font-weight: 600;">Hello{{ user }}</a>
                
        {% endif %}
        <a class="navbar-brand but"  id="hrp" href="#">Search-IT-Event</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation" id="dropMenu">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse navbar-right" id="navbarNavAltMarkup">

            <div class="navbar-nav ml-auto navbar-right">
                
                <a class="nav-item nav-link ml-4 active butPage" href="#" id="now" >Events</a>
                
                <a class="nav-item nav-link ml-4 butPage" href="{% url 'register' %}">Register Event</a>
                
                <a class="nav-item nav-link ml-4 butPage" href="{% url 'forum' %}">Forum</a>
                
                <a class="nav-item nav-link ml-4 butPage" href="{% url 'about_us:aboutus' %}">About Us</a>

                {% if user.is_authenticated %}
                
                <a class="nav-item nav-link ml-4 butPage" href="{% url 'logout' %}" id="logout">Logout</a>
                
                {% else %}
                
                <a class="nav-item nav-link ml-4 butPage" href="{% url 'login' %}">Login</a>
                
                {% endif %}
                
            </div>
        </div> 
    </nav>

    
    <div class="container-fluid">
        {% block content %}
        {% endblock %}
    </div>

    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
        integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
        crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"
        integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1"
        crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"
        integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM"
        crossorigin="anonymous"></script>

</body>

</html>

Events/templates/searchevents.html
{% extends 'navbar.html' %}
{% load static %}

{% block content %}

<link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}" >
    <br><br><br>
    <ul id="butColor">
        <li id="butLi">
            <span class="mode">Dark</span>
            <span class="mode">Light</span>
        </li>
    </ul>
    
    
    <div class="header">Search Event</div>
    <form method="POST">
        {% csrf_token %}
        <table>
            <div class="form-group">
                {{ form }}
        </div>
        </table>
        <br><br>
        <div class="submitBtn">
            <button type="submit" class="btn btn-primary">
                SUBMIT
            </button>
        </div>
    </form>
</div>

{% endblock %}

<!-- <script src="https://code.jquery.com/jquery-3.4.1.js"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.0/jquery.min.js"></script>
    <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
<script type="text/javascript" src="{% static 'Events.js' %}"></script> -->